[CREATE] CategoryView, ProductView, ProductDetailView 구현
wecode-bootcamp-korea/25-1st-HandWash-backend pull request #6
Opened 2021-10-11 12:40 UTC by thisisempty

products/views.py : CategoryView, ProductView, ProductDetailView

[ADD]
products/urls.py : Add View path
handwash/urls.py : Add app path

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 에러 핸들링 추가
- 모든 카테고리 가져오는 뷰 : CategoryView
- 상품 필터링 뷰(카테고리, 가격, 핏, 사이즈, 컬러, 길이...) : ProductListView
  - 동일한 제품의 여러 컬러가 한번에 보이는 것 수정 -> mysql의 distinct는 field name을 사용할 수 없어서 postgresql로 데이터베이스를 변경하였습니다.
  - offset & limit 사용한 pagenation 구현
  - 변수명 수정
- 제품 상세 정보 뷰 : ProductDetailView
  -  변수명 수정

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 카테고리 뷰 
 - 접근 할 수 있는 모든 카테고리를 가져온다

2. 제품 필터링 & 정렬 
 - dictionary를 사용한 제품 필터링
 - url 파라미터를 사용한 제품 정렬
 - 같은 상품 다른 컬러일 경우 한번만 불러오도록 함

3. images table ->sub_images와 main_images로 분리

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 딕셔너리 key : value로 if문을 여러 번 사용할 필요없이 필터링 할 수 있었다.
- mysql에서 제공하지 않아 postgresql로 변경 후 원하는 기능을 구현할 수 있었다.
<br />

## :: 기타 질문 및 특이 사항

2021-10-12 00:46 UTC, lordmyshepherd requested changes

2021-10-12 00:46 UTC, lordmyshepherd commented on products/views.py
> +class ProductView(View) :
상품 목록을 반환하는 엔드포인트라면 class명을 복수로 만들어주세요.
`class ProductsView` 또는 `class ProductListView`

```suggestion
```

2021-10-12 00:46 UTC, lordmyshepherd commented on products/views.py
> +    order_request = request.GET.get('sort')
상품 목록을 요청할 때, `offset`과 `limit`을 받도록 만들어주시고, limit에 제한을 걸어두셔야 합니다.
그 이유는 만약에 데이터베이스에 상품이 10만개일 때, client의 요청에 따라 모든 상품을 반환하게 된다면 부하가 많이 걸리겠죠?
그렇기 때문에 서버단에서 요청마다 자원의 개수를 제한해둬야 합니다.

보통은 limit으로 100을 많이 사용합니다.

2021-10-12 00:46 UTC, lordmyshepherd commented on products/views.py
> +    except :
Filtering 조건에 맞는 상품이 없는 경우 error를 발생하는 것이 아니라 empty list를 반환해야 합니다.

2021-10-12 00:46 UTC, lordmyshepherd commented on products/views.py
> +    except :
이에 맞게 코드를 수정해주세요.

2021-10-12 00:46 UTC, lordmyshepherd commented on products/views.py
> +        'image'         : [i.url for i in product.image_set.all()][0:2]
변수명을 명확하게 선언해주세요. `복수인지 단수인지`, `i` 는 피해주세요.
```suggestion
        'images'         : [image.url for image in product.image_set.all()][0:2]
```

2021-10-12 00:46 UTC, lordmyshepherd commented on products/views.py
> +        'color'         : [i.color for i in products.filter(name=product.name)],
이름이 같은 모든 상품들의 컬러를 반환해줘야 하는 이유가 있나요?
```suggestion
        'colors'         : [product.color for product in products.filter(name=product.name)],
```

2021-10-12 00:46 UTC, lordmyshepherd commented on products/views.py
> +        'main_image'    : [i.url for i in product.image_set.all()][0:2],
Index로 이미지를 구분하면, 순서가 잘 못 들어가 있는 경우 디버깅하기 어려울 것 같습니다.
`[0:2] -> main_image`와 같은 방법 말고 다른 방법은 없을까요?

2021-10-12 00:46 UTC, lordmyshepherd commented on products/views.py
> +      product = Product.objects.get(id=product_id)
`objects.get()`호출 시 매칭되는 데이터가 없는 경우에 발생할 수 있는 error를 추가해주세요.

2021-10-12 00:46 UTC, lordmyshepherd commented on products/views.py
> +    except :
단순히 except만 사용하는 것을 피해주세요. 디버깅하기가 어려워집니다. `Objects.get` 호출 시 발생하는 에러에 대해서만 핸들링 해주세요. ` hint) Product.DoesNot..`

2021-10-12 00:46 UTC, lordmyshepherd commented on products/views.py
> +class CategoryView(View) :
3중 for문을 사용하지 않고 만들 수 있는 방법은 없을까요?

2021-10-12 00:59 UTC, thisisempty commented on products/views.py
> +        'color'         : [i.color for i in products.filter(name=product.name)],
h&m 사이트를 보면 아래 사진과 같이 같은 제품의 색을 표시합니다. 
연관제품 테이블을 생성하지 않아서 일단은 이름이 같은제품으로 필터링 했습니다.
<img width="520" alt="스크린샷 2021-10-12 오전 9 59 09" src="https://user-images.githubusercontent.com/86424094/136872909-534b6ba4-8d84-4301-957b-acb7024d9550.png">

2021-10-14 02:42 UTC, lordmyshepherd commented
LGTM 👍

2021-10-14 02:42 UTC, merged